### ISSUE TITLE
Does it use parameter binding?

### ISSUE THREAD

**Issue by vickyRathee** [cdroulers/awesome-sql-builder#4]
The where clause is string with field name, operator and value all in one string. Does It uses parameter binding to protect my application against SQL injection attacks?

Or there is need to clean strings being passed? Ideally it should be 
``
Where("FieldName", Equal.To, "Some value")
``

**Comment by cdroulers** [comment]
Hey!

Good question! But this package only deals in creating the string. It doesn't execute them in any way. That's up to you to use them properly with either ADO.NET or whatever ORM you are using.

Since it gives a string, you can put parameter names in there, like

```
.Where("u.Name LIKE @Query")
```
Then, when you use ADO.NET, you can do
```
cmd.Text = sqlStatement.ToString();
cmd.Parameters.AddWithValue("@Query", "%" + userInput + "%");

var dr = cmd.ExecuteDataReader();
```

Hope this helps! Glad to see someone using this! Don't hesitate to create a PR if necessary!

**Comment by cdroulers** [comment]
Added documentation

https://github.com/cdroulers/awesome-sql-builder#using-with-adonet
