### ISSUE TITLE
Discontinued?

### ISSUE THREAD

**Issue by Flying--Dutchman** [cdroulers/awesome-sql-builder#5]
Hello,

the last commit is almost 2 years ago, are there any plans to continue this project?

**Comment by cdroulers** [comment]
Hey, I haven't been using it for any project myself, but it's still working as far as I know! If you have features you'd like, do open an issue and / or submit a PR! If I have time, I can work on it!

**Comment by Flying--Dutchman** [comment]
That sounds great! 
I would also need INSERT, UPDATE and DELETE functions. If you need help with those, just let me know.
An Postgresql renderer will be added by me by the end of the week.

I really like the fact that this project only creates the SQL-String and has no actuall DB-Handling, like all those other SQLBuilders.

**Comment by cdroulers** [comment]
Yeah, I wanted something to build queries to pass off to Dapper and all the other frameworks wanted to handle the DB part.

I'll create issues for INSERT, UPDATE and DELETE. For Delete, it would only require a table name and WHERE to start, I imagine.

Insert and Update, do you see specific requirements? Like passing in a list of properties to create the list of columns to insert or update? I don't think I want to touch actual parameter binding, but since there's already a renderer interface, creating the parameter string (@Param in SQL and :param in mysql (maybe)) should be decently easy. Then, parameters can be added by the caller.

Let's iron out the details and I'll create the issues.

I created a Gitter so we can talk!

https://gitter.im/awesome-sql-builder/Lobby#

**Comment by cdroulers** [comment]
Closing, as all requests are tracked in different issues.
INSERT #7 
UPDATE #8 
DELETE #9 
PostGreSQL #11
